### ISSUE TITLE
Asking for contact

### ISSUE THREAD

**Issue by ABDELBAKI-Mohamed** [rahu1ramesh/essential-code#1]
Hello Mr Rahul Ramesh. I couldn't find another way to contact you. We are a team of a developpers trying to get the hang of Bahmni, and we have noticed that you have made contributions on the atomfeed repository, so I am contacting you here, if you can please reply back, we have a couple of questions, and if possible, we could use your services, either as a collaboration work or as commissioned freelance work. Thank you very much for your time. You can e-mail me at abdelbaki.mo6@gmail.com.

**Comment by rahu1ramesh** [comment]
Hey @ABDELBAKI-Mohamed, 

Thank you for reaching out. Bahmni developers are always ready to assist anyone getting started with Bahmni. Here are some channels you can use to connect with us:

[Product Architecture Team (PAT) Calls](https://bahmni.atlassian.net/wiki/spaces/BAH/pages/414646273/Communication+Channels+and+Tools+Discourse+Slack): PAT calls are an intersection of product and technical thinkers, focusing on the evolution of the Bahmni software product. These calls are open for anyone to attend and are held every Wednesday at 1 pm UTC (6:30 pm India).

[Discussion Forum](https://talk.openmrs.org/t/welcome-please-introduce-yourself-to-the-bahmni-community/16001): The Bahmni discussion forum is the primary platform for communication. You can introduce yourself, suggest product enhancements, seek troubleshooting assistance, and more.

[Slack](https://bahmni.slack.com/): Bahmni contributors actively use Slack for quick chat-style messages. You can join our Slack workspace using the provided link. Most team members are online during India timezone on weekdays.

If you have any questions or need assistance, feel free to ping your query in any of the channels mentioned above. We look forward to assisting you further.

**Comment by ABDELBAKI-Mohamed** [comment]
Hello Mr Rahul Ramesh,

Thank you very much for your response, I am already in the slack community.
As a team, we have so many questions to ask and it just seems like separate
messages won't get us the kind of expertise returns we are looking for. Is
there any chance we can plan a call with yourself or someone you recommend
to help us shed some light on the working of bahmni as a whole and on some
specific questions our team might ask?

Thank you again for your time, and for the fast response.

ABDELBAKI Mohamed
Modoock
